DELETE FROM FILM_GENRES;
DELETE FROM FILM_LIKES;
DELETE FROM FILMS;
DELETE FROM USER_FRIENDS;
DELETE FROM USERS;

ALTER TABLE FILMS ALTER COLUMN FILM_ID RESTART WITH 1;
ALTER TABLE USERS ALTER COLUMN USER_ID RESTART WITH 1;