MERGE INTO MPA_RATING (RATING_ID, RATING_VALUE) VALUES (1, 'G');
MERGE INTO MPA_RATING (RATING_ID, RATING_VALUE) VALUES (2, 'PG');
MERGE INTO MPA_RATING (RATING_ID, RATING_VALUE) VALUES (3, 'PG-13');
MERGE INTO MPA_RATING (RATING_ID, RATING_VALUE) VALUES (4, 'R');
MERGE INTO MPA_RATING (RATING_ID, RATING_VALUE) VALUES (5, 'NC-17');

MERGE INTO GENRES (GENRE_ID, GENRE) VALUES (1, 'Комедия');
MERGE INTO GENRES (GENRE_ID, GENRE) VALUES (2, 'Драма');
MERGE INTO GENRES (GENRE_ID, GENRE) VALUES (3, 'Мультфильм');
MERGE INTO GENRES (GENRE_ID, GENRE) VALUES (4, 'Триллер');
MERGE INTO GENRES (GENRE_ID, GENRE) VALUES (5, 'Документальный');
MERGE INTO GENRES (GENRE_ID, GENRE) VALUES (6, 'Боевик');
